### ISSUE TITLE
Improve Hyperlink Contrast for Password Reset Email

### ISSUE THREAD

**Issue by penoptech** [Get-Your/Get-Your#111]
Below is a picture of the password reset email we send to our users. We need to improve the contrast of the hyperlinks, so users can actually see the links.

![image](https://user-images.githubusercontent.com/55520784/233796843-9ba605cc-f3d4-4260-9ce2-9240fd10b703.png)

**Comment by TiCampbell** [comment]
Now that our program admin has access to the email templates, this is going to be transferred to them. Closing as outside our purview.
