### ISSUE TITLE
'Back' arrow when uploading files is a long process to get back to program selection

### ISSUE THREAD

**Issue by TiCampbell** [Get-Your/Get-Your#12]
The 'back' arrow in the 'file upload' step uses `history.back()`, which makes it potentially a long process to get back to the program selection. Either need to simplify the page loads between 'program selection' and 'file upload' or change the 'back' arrow to link directly to the 'program selection' page.

**Comment by penoptech** [comment]
@TiCampbell - This should be addressed in v2 now
