### ISSUE TITLE
Logging Out After Uploading Files Doesn't Save Progress

### ISSUE THREAD

**Issue by penoptech** [Get-Your/Get-Your#133]
On the `File Upload` page, I uploaded 1 of 3 files and clicked the `Save & Logout` button. When I logged back in I wasn't taken back to the `File Upload` page, but instead was taken to the `Eligibility` page. The expected behavior would have been to be redirected back to the `File Uploaded` page, with only two files left to upload.

**Comment by TiCampbell** [comment]
This has been an ongoing problem with `what_page()` - the generic Issue is #92.
