### ISSUE TITLE
Missing 'Category' for IQ Program Lists and Qualified Programs Pages

### ISSUE THREAD

**Issue by penoptech** [Get-Your/Get-Your#136]
Below the title of every IQ program on the `Program Lists` and `Qualified Programs` pages there's a `Category` (like Recreation Assistance or Connexion Assistance), but these are currently missing. See screenshot below for reference.

<img width="1198" alt="Screenshot 2023-05-07 at 9 24 22 AM" src="https://user-images.githubusercontent.com/55520784/236687088-10fdfc29-1de2-48e0-972e-9ef3d3a7b21e.png">

**Comment by penoptech** [comment]
@TiCampbell - That makes sense to me, especially as more programs are added.  Do you think we can have this as an enhancement after the new v2 release?

**Comment by TiCampbell** [comment]
@penoptech Yep let's leave it for later. I just created #149 to add this.

So we don't have to have too many database changes, I'm thinking maybe hardcoding is the way to go for now...?
