### ISSUE TITLE
Failed to Auto Apply User for Grocery Rebate

### ISSUE THREAD

**Issue by penoptech** [Get-Your/Get-Your#138]
When a user selects an eligibility program that puts their AMI <= 30%, that user should automatically be enrolled in the `Grocery Rebate` program. When I completed an application and selected the ACP eligibility program, I wasn't automatically enrolled in the `Grocery Rebate` program. My guess this will happen regardless of the eligibility program a user selects.

<img width="752" alt="Screenshot 2023-05-07 at 9 48 33 AM" src="https://user-images.githubusercontent.com/55520784/236688155-802d1cbb-6510-44b5-a7e7-e7aafecc00cf.png">

**Comment by TiCampbell** [comment]
I had the same issue with Medicaid, so it does indeed happen with other eligibility programs as well.
