### ISSUE TITLE
Missing Dashboard 'Welcome' Modal

### ISSUE THREAD

**Issue by penoptech** [Get-Your/Get-Your#139]
When a user first navigates to their dashboard after completing their application, they should be greeted with a modal that welcomes them to their dashboard and gives them a brief description of how to apply for programs they're eligible for. Below is an example of what we currently have in production.

<img width="1201" alt="Screenshot 2023-05-07 at 10 08 13 AM" src="https://user-images.githubusercontent.com/55520784/236689249-51d7d29a-87d2-438e-aac5-c20b8b95d60d.png">

**Comment by TiCampbell** [comment]
We should also add something like "If you don't see a program you're expecting or are having an issue, please call xxx-xxx-xxxx".
