### ISSUE TITLE
Income Financial Verification Popup clarity

### ISSUE THREAD

**Issue by TiCampbell** [Get-Your/Get-Your#14]
The Income Financial Verification popup (originally changed in Get-Your/GetFoco#128) now gives a success message when the file is successfully uploaded. The success message is a great addition, but we'd like to have it *combined* with the initial instructional popup instead of replacing it.

There would be no change to the first time the file upload page loads, then every time after a successful upload, the 'success' message could be added to the top of the instructions in the same modal. This way we could have both confirmation of previous upload and instructions for current upload in a single modal.

**Comment by penoptech** [comment]
@TiCampbell - I think this is fixed in both V1 and V2 now.

**Comment by TiCampbell** [comment]
@penoptech Yep, I agree.
