### ISSUE TITLE
Account for buffer when calculating effective date for renewals

### ISSUE THREAD

**Issue by TiCampbell** [Get-Your/Get-Your#305]
The built-in buffer for renewals is an important user-friendliness feature, but it adds a bit of complexity for when renewals are "effective". For the case of an applicant applying on 2025-01-01, they would receive their Grocery Tax Rebate for 2025 in January. From the app, they would receive their renewal notification on 2025-12-01, and if they then completed their renewal immediately, without accounting for the buffer they could conceivably receive a *second* Grocery Tax Rebate for 2025, which can't be allowed.

**Comment by TiCampbell** [comment]
I propose an `eligibility_applicable_after` field to the `IQProgram` table. As an application is finalized, the will be the current timestamp if `last_completed_at` is NULL, else `last_completed_at+renewal_interval_months`.

Then the coordinator admin panel will allow filtering to different levels (year, year&month, …), which will enable each program to decide how to handle enrollments (so in the case in the description, `eligibility_applicable_after` would be '2026-01-01'.

**Comment by TiCampbell** [comment]
This actually doesn't need to be done by v4 (the changes can be ETL'd later); moving to v4.1 Release.

**Comment by penoptech** [comment]
@TiCampbell - I might be thinking about this the wrong way or maybe misunderstanding something. If I understand how the `enrollment_applicable_after` field should be populated it would go like:

```pseudo
if app_user.last_completed_at is null:
      iqprogram.applied_at = now()
      iqprogram.enrolled_at = null
      iqprogram.enrollment_applicable_after = now()
else:
      iqprogram.applied_at = now()
      iqprogram_enrolled_at = null
      iqprogram_enrollment_applicable_after = last_completed_at + renewal_interval_months
```

Assume a user renews as soon as they're notified and that their renewal is annual. If we extrapolate this out over, multiple renewals cycles:

Initial Application
    Last Completed At: 3/1/2023
    Applied At (Program A): 3/1/2023
    Enrollment Applicable After (Program A): 3/1/2023

First Renewal
    Last Completed At: 2/1/2024
    Applied At (Program A): 2/1/2024
    Enrollment Applicable After (Program A): 3/1/2024

Second Renewal
    Last Completed At: 1/1/2025
    Applied At (Program A): 1/1/2025
    Enrollment Applicable After (Program A): 2/1/2025

Third Renewal
    Last Completed At: 12/1/2025
    Applied At (Program A): 12/1/2025
    Enrollment Applicable After (Program A): 1/1/2026

Forth Renewal
    Last Completed At: 11/1/2026
    Applied At (Program A): 11/1/2026
    Enrollment Applicable After (Program A): 12/1/2026

We're going to experience this drift if we decide the support the notification buffer as-is. We might want to reconsider this feature altogether.

**Comment by TiCampbell** [comment]
@penoptech Ah, great catch on the drift! You're absolutely right, this won't work after all. Good idea to remove it for now - I'm going to merge PR #307.

The idea of queuing renewals until `last_completed_at+<renewal interval>` would definitely solve this issue, my only concern is that on users' dashboards it would look like the programs were just sitting there in PENDING for up to a month with no explanation.

**Comment by TiCampbell** [comment]
Closing as unnecessary; see my last comment.
