### ISSUE TITLE
Update the Connexion email notification to clarify that it's not actually signing up for service

### ISSUE THREAD

**Issue by TiCampbell** [Get-Your/Get-Your#4]
Add wording to make it clear that this confirmation of successful enrollment in Reduced-Rate Connexion is just for the rate, not actually signing up for service. The user will still have to call Connexion to set up new service; this just means that they'll have a record of the user to then apply the reduced rate.

**Comment by penoptech** [comment]
@TiCampbell - We've got this covered in v2 now as well. The new verbiage is on line 28 of the `quick_apply.html` file

**Comment by TiCampbell** [comment]
@penoptech Perfect!
