### ISSUE TITLE
File upload workflow doesn't work correctly if an incorrect-type file is uploaded

### ISSUE THREAD

**Issue by TiCampbell** [Get-Your/Get-Your#58]
**Describe the bug**
On the file upload screen (Step 5), the workflow for catching a file of an incorrect type (e.g. not PDF, PNG, or JPEG) isn't directing the user properly

**To Reproduce**
1. Go through the application and get to Step 5 (file uploads). For the following steps, in Step 4 I had selected SNAP, Free and Reduced Lunch, and Medicaid
2. Upload a SNAP file with the correct type.
3. Once SNAP has been uploaded, upload an *incorrect* type as Free and Reduced Lunch file: 
![image](https://user-images.githubusercontent.com/44819630/218858658-6253e624-f175-46bf-a4a9-b7c326834d74.png)
4. The page will refresh with a 'not a valid file type' error message and direct the user to re-upload the Free and Reduced Lunch file:
![image](https://user-images.githubusercontent.com/44819630/218858855-54035cee-eb7b-4a10-b79c-58bba00d8afe.png)
An issue for the remaining steps seems to be that there aren't any options in the 'Files:' list:
![image](https://user-images.githubusercontent.com/44819630/218858943-bd1597da-6d87-4a1e-ac08-74881d9b46fa.png)
5. Even though there are no available options in the 'Files:' list, upload a file of a *correct* type. The page will refresh with a 'this field is required' error:
![image](https://user-images.githubusercontent.com/44819630/218857328-a9cd78c4-f292-4f28-8979-bf6e7f36e17f.png)
The file you just attempted to upload (of a *correct* type) is not stored anywhere, so the user has to re-upload that file for the Free and Reduced Lunch file. Furthermore, the 'please upload your...' prompt refills with **all** programs, even though the SNAP file was saved correctly, forcing the user to upload all files regardless of whether any have previously been uploaded.

**Expected behavior**
The expectation is that step 4 (in the 'reproduce' section) will direct the user to re-upload the *same file they had just attempted* and will save the file exactly as if they had uploaded the correct file the first try. Then it will redirect back to the primary workflow, where only the remaining files will need to be uploaded.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 109.0.1

**Comment by penoptech** [comment]
@TiCampbell - I think we'll be able to close this out with the V2 release now.
