### ISSUE TITLE
Support Dynamically Adding Programs (like SNAP or Medicaid)

### ISSUE THREAD

**Issue by penoptech** [Get-Your/Get-Your#65]
The objective here is to add programs (like Medicaid or SNAP) on the fly to Get FoCo without making any code changes. Here are two approaches I took to modeling out the new table structure.

[programs_erd.pdf](https://github.com/Get-Your/GetFoco/files/10986105/programs_erd.pdf)

**Comment by TiCampbell** [comment]
This has now been fully implemented in the `EligibilityProgramRD` model (and corresponding `app_eligibilityprogramrd` table).
