### ISSUE TITLE
Update dashboard to only show the 'welcome' popup on the first visit

### ISSUE THREAD

**Issue by TiCampbell** [Get-Your/Get-Your#66]
Currently the welcome message that specifies '...all you need to do now is to click on Quick Apply + for programs you may be interested in to apply...' shows every time the `dashboard_GetFoco.html` page loads, which is unnecessary and potentially annoying. Create persistent flag to only show ‘welcome’ popup on the first visit.

**Comment by penoptech** [comment]
@TiCampbell - This is a part of the v2 release.
