### ISSUE TITLE
Guard Endpoints that Require an Authenticated User

### ISSUE THREAD

**Issue by penoptech** [Get-Your/Get-Your#70]
Currently anyone can navigate to pages using URLs. For example without logging in, I can immediately navigate to https://getfoco.fcgov.com/application/programs and start selecting programs. This shouldn't be allowed to happen. The impacts could be benign from a security stand point, but that's just an assumption. It certainly is not great from a UX perspective, because a user might bookmark a page (like their dashboard) that requires them to be authenticated. When they use their bookmark they're just met with 500 error or a page that they can interact with but isn't necessarily connected to their account.

Django does support plugging into their middleware pipeline, so we could implement something through the settings and middleware to prevent users from navigating to these pages and redirecting them to login if they attempt to

**Comment by TiCampbell** [comment]
This was fixed in #234.
