### ISSUE TITLE
Upgrade dependency versions

### ISSUE THREAD

**Issue by TiCampbell** [Get-Your/Get-Your#76]
Dependency versions haven't been addressed in a while - time to update. Also call out major versions for all packages that make sense to do so.

Since this is such a broad change, update `Dockerfile` pip installs as well as `requirements.txt`.

**Comment by jshrimp29** [comment]
@penoptech I broke out `azure-storage-blob` into its own Issue (#168), so please update this as-needed for the remaining dependencies (I think you said you had looked into the rest of them).

**Comment by penoptech** [comment]
@TiCampbell - I think we between the updates we've both made we're good to close this issue, right?

**Comment by TiCampbell** [comment]
@penoptech Agreed!
