### ISSUE TITLE
On mobile, only the 'programs you may qualify for' links to the dashboard/qualifiedPrograms page

### ISSUE THREAD

**Issue by TiCampbell** [Get-Your/Get-Your#8]
![Image](https://user-images.githubusercontent.com/44819630/214106091-c7e68402-2b9b-4c78-902c-1771391e5b75.png)

The 'programs active' and 'pending approval' areas don't appear to be links at all; only the 'programs you may qualify for' button links to the `dashboard/qualifiedPrograms` page. The issue is that this page has _all_ programs, so the other areas in the dashboard should also be buttons to this `qualifiedPrograms` page.

![Image](https://user-images.githubusercontent.com/44819630/214106636-9a291a0b-83d9-46dd-bc96-a2ca4cf19b6c.png)

OR, we split up the programs into separate pages for 'active', 'pending approval', and 'may qualify for' and have each link to their respective page.

**Comment by penoptech** [comment]
@TiCampbell - This is can probably be closed out as a part of the V2 release
